### ISSUE TITLE
支持 Snap Genshin 成就格式

### ISSUE THREAD

**Issue by Lightczx** [HolographicHat/genshin-achievement-export#6]
你好，我是 [Snap.Genshin](https://github.com/DGP-Studio/Snap.Genshin) 的主要维护者
你的项目做的非常不错，但是导出的结果中并没有我们能够较好的处理的格式
请问能否支持以下的格式(或比较类似的格式)的导出呢：
``` json
[
    {
        "Id" : 80001,
        "DateTime" : "yyyy-MM-dd HH:mm:ss"
    },
    {...},
    ...
]
```
其中应当仅包含已完成的成就的Id与时间，字段的名称可以变通
但我认为`Id`与`完成时间`是必不可少的。

**Comment by Lightczx** [comment]
目前已经决定采用椰羊的格式导入

**Comment by HolographicHat** [comment]
> 目前已经决定采用椰羊的格式导入

椰羊的导出方式将在下版本更新 (55f1ce3d557603f411a8badffd0dfb57cf50308f)
对SnapGenshin的支持: ea168ce96be725f5a39af4b39b9eab954655b0c7
