### ISSUE TITLE
网络错误，请检查网络后重试 (21-1)

### ISSUE THREAD

**Issue by flymousechiu** [HolographicHat/genshin-achievement-export#7]
版本: 

1.5

环境:

Edition	Windows 11 Home
Version	22H2
Installed on	‎4/‎7/‎2022
OS build	22593.1
Experience	Windows Feature Experience Pack 1000.22593.1.0

**Comment by flymousechiu** [comment]
`./secret` 在`.gitignore`里面没有上传, 不知道相应的错误代码是什么引起的.

**Comment by flymousechiu** [comment]
用fiddler未能检测到http request. 可能是相应的代码不适用于现有平台.

**Comment by HolographicHat** [comment]
请说明所在地区（精确到省/市）或IP地址 以及出现问题时的大致时间（越精确越好）

**Comment by HolographicHat** [comment]
> 用fiddler未能检测到http request. 可能是相应的代码不适用于现有平台.

GAE的HTTP请求在一般情况下不经过系统代理

**Comment by flymousechiu** [comment]
美国, 马萨诸塞州(fios)

**Comment by HolographicHat** [comment]
尝试一下这个版本：
https://github.com/HolographicHat/genshin-achievement-export/releases/download/1.5.50/YaeAchievement-DevBuild-04132056.exe
启动一次后，打开```config.json```，将```oversea_api```的值设置为```true```后重试

**Comment by HolographicHat** [comment]
> 可以了. 啥云会block境外的ip访问的么...?

默认是腾讯云(成都)(
