### ISSUE TITLE
网络错误，请检查网络后重试 (21-1)

### ISSUE THREAD

**Issue by gongfuture** [HolographicHat/genshin-achievement-export#8]
一开始如https://github.com/HolographicHat/genshin-achievement-export/issues/7 问题一样
在下载了1.5.50并修改config后，启动出现如下字样：

19:27:01 检查更新
19:27:02 有可用更新: 1.5 => undefined
19:27:02 更新内容:
undefined
19:27:02 下载地址: https://github.com/HolographicHat/genshin-achievement-export/releases

网络错误，请检查网络后重试 (22-1)
按任意键退出

**Comment by HolographicHat** [comment]
请说明地区/IP、运营商信息

**Comment by gongfuture** [comment]
117.136.67.238
中国 江苏省 镇江市 移动

**Comment by HolographicHat** [comment]
国内用户不要使用OverseaAPI(
ping一下 service-qrcf9kwz-1259389942.cd.apigw.tencentcs.com 看看？

**Comment by gongfuture** [comment]
ping通了，但是1.5连不上

**Comment by gongfuture** [comment]
要不然也不会用1.5.50了（

**Comment by gongfuture** [comment]
试了半天，估计是网络抽风，刚刚1.5终于可以用了

**Comment by gongfuture** [comment]
:-)
