### ISSUE TITLE
paimon.moe 导出格式问题

### ISSUE THREAD

**Issue by gaoyifan** [HolographicHat/genshin-achievement-export#9]
您好，感谢您创作的便捷的导出工具。

在使用过程中发现一个小问题，希望有空能检查一下。感谢~ 

导出为 paimon.moe 格式，JSON 结果：
```
{"achievement":{"[object Object]":{"80001":true,"80002":true,"80003":true,...}
```

初步分析：按照预期这里是个字符串，实际上是个对象：
https://github.com/HolographicHat/genshin-achievement-export/blob/4417feab53be7f53094f0618a64bd6eb6351e6e8/export.js#L22

修改草案：
```js
const gid = data["a"][id]["g"]
```

环境
* Windows 10
* 国际服
* YaeAchievement-Release-04162110

**Comment by HolographicHat** [comment]
感谢支持
